---
- ros_topic_name: "/explorer_ds1/cmd_vel"
  gz_topic_name: "/explorer_ds1/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "/explorer_ds1/pose"
  gz_topic_name: "/model/explorer_ds1/pose"
  ros_type_name: "geometry_msgs/msg/PoseStamped"
  gz_type_name: "gz.msgs.Pose"
  direction: GZ_TO_ROS

- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# Enable Quadrotor command configuration.
# - topic_name: "/explorer_ds1/enable"
#   ros_type_name: "std_msgs/msg/Bool"
#   gz_type_name: "gz.msgs.Boolean"
#   direction: ROS_TO_GZ

# rgb_camera_bridge configuration.
- ros_topic_name: "/explorer_ds1/rgb_camera/image_raw"
  gz_topic_name: "/explorer_ds1/rs_front/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/explorer_ds1/camera_info"
  gz_topic_name: "/explorer_ds1/rs_front/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# depth_camera_bridge configuration.
- ros_topic_name: "/explorer_ds1/depth_camera/image_raw"
  gz_topic_name: "/explorer_ds1/rs_front/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# 3d_lidar_bridge configuration.
- ros_topic_name: "/explorer_ds1/lidar/scan"
  gz_topic_name: "/explorer_ds1/front_laser"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/explorer_ds1/lidar/point_cloud"
  gz_topic_name: "/explorer_ds1/front_laser/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

# imu_bridge configuration.
- ros_topic_name: "/explorer_ds1/imu"
  gz_topic_name: "/explorer_ds1/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS
