---
- ros_topic_name: "/explorer_ds1/cmd_vel"
  gz_topic_name: "/explorer_ds1/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS


- ros_topic_name: "/tf"
  gz_topic_name: "/model/diff_drive/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
  
- ros_topic_name: "/tf_static"
  gz_topic_name: "/model/diff_drive/pose_static"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# Robot 1
# Velocity command configuration.
- topic_name: "/bebop1/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  lazy: true
  direction: ROS_TO_GZ

# Motor speed command configuration.
- topic_name: "/bebop1/gazebo/command/motor_speed"
  ros_type_name: "std_msgs/msg/Float32"
  gz_type_name: "gz.msgs.Float"
  lazy: true
  direction: ROS_TO_GZ

# Enable Quadrotor command configuration.
- topic_name: "/bebop1/enable"
  ros_type_name: "std_msgs/msg/Bool"
  gz_type_name: "gz.msgs.Boolean"
  lazy: true
  direction: ROS_TO_GZ

# Pose state configuration.
- topic_name: "/bebop1/pose"
  ros_type_name: "geometry_msgs/msg/Pose"
  gz_type_name: "gz.msgs.Pose"
  lazy: true
  direction: GZ_TO_ROS

# Initial Pose configuration.
- topic_name: "/bebop1/set_pose"
  ros_type_name: "geometry_msgs/msg/Pose"
  gz_type_name: "gz.msgs.Pose"
  lazy: true
  direction: ROS_TO_GZ

# rgbd_camera_bridge configuration.
- topic_name: "/world/bebop/model/bebop1/link/body/sensor/rgb_camera_sensor/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  lazy: true
  direction: GZ_TO_ROS

- topic_name: "/world/bebop/model/bebop1/link/body/sensor/rgb_camera_sensor/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  lazy: true
  direction: GZ_TO_ROS